name: Deploy

on:
  push:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout@v2
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_CREDENTIALS }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        run: gcloud functions deploy issue --runtime nodejs12 --trigger-http --allow-unauthenticated --project="${{ secrets.GCP_PROJECT_ID }}"
