name: Deploy

on:
  push:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout@v2
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        
      - name: Print node version
        run: node --version
